In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
cols = ['event_name', 'event_location', 'event_summary', 'event_description', 'category']
df = pd.read_csv('events.csv', names=cols, skiprows=1)
df = df.sample(frac=1).reset_index(drop=True)
df.head()

,event_name,event_location,event_summary,event_description,category
0,Hobby Candle Carving,Craft Cellar,Carve patterns into candles,"Relaxing, decorative hobby, customize gifts.",Personal
1,Morning Yoga Class,City Fitness Studio,Gentle yoga flow for all levels,"Improve flexibility, balance, and mental focus...",Fitness
2,Onboarding New Hires,HR Training Suite,Introduce new employees to the company,"Cover policies, culture, and assign mentors fo...",Work
3,Evening Rollerblading Crew,City Sidewalks,Group inline skating,"Intermediate pace, explore safe bike paths.",Fitness
4,Unmarked Door Admiration,Mysterious Door,NaN,NaN,Others

# Drop the feature with minimal predictive power

In [ ]:
df.drop('event_location', axis=1, inplace=True)

In [ ]:
df.head()

,event_name,event_summary,event_description,category
0,Hobby Candle Carving,Carve patterns into candles,"Relaxing, decorative hobby, customize gifts.",Personal
1,Morning Yoga Class,Gentle yoga flow for all levels,"Improve flexibility, balance, and mental focus...",Fitness
2,Onboarding New Hires,Introduce new employees to the company,"Cover policies, culture, and assign mentors fo...",Work
3,Evening Rollerblading Crew,Group inline skating,"Intermediate pace, explore safe bike paths.",Fitness
4,Unmarked Door Admiration,NaN,NaN,Others

# Preprocess the event_name, event_summary, event_description into numerical values

In [ ]:
from nltk.corpus import stopwords
import nltk
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
import string
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [ ]:
def preprocess_text(text):
    # Lowercase text
    text = text.lower()
    # Remove punctuation
    text = ''.join([char for char in text if char not in string.punctuation])
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    lemmatizer = WordNetLemmatizer()
    words = text.split()
    cleaned_words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]
    return ' '.join(cleaned_words)

In [ ]:
df.fillna('missing', inplace=True)

In [ ]:
df['combined_text'] = df['event_name'] + ' ' + df['event_summary'] + ' ' + df['event_description']
df['combined_text'] = df['combined_text'].apply(preprocess_text)

In [ ]:
from sklearn.feature_extraction.text import HashingVectorizer

vectorizer = HashingVectorizer(n_features=100000, norm='l2', alternate_sign=False)
hashing_matrix = vectorizer.transform(df['combined_text'])

In [ ]:
import pickle

with open('vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

In [ ]:
label_encoder = LabelEncoder()
df['encoded_category'] = label_encoder.fit_transform(df['category'])
category_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))

print("Category Mapping:")
for label, encoding in category_mapping.items():
    print(f"{label}: {encoding}")

Category Mapping:
Academics: 0
Fitness: 1
Others: 2
Personal: 3
Social: 4
Work: 5

In [ ]:
df

,event_name,event_summary,event_description,category,combined_text,encoded_category
0,Hobby Candle Carving,Carve patterns into candles,"Relaxing, decorative hobby, customize gifts.",Personal,hobby candle carving carve pattern candle rela...,3
1,Morning Yoga Class,Gentle yoga flow for all levels,"Improve flexibility, balance, and mental focus...",Fitness,morning yoga class gentle yoga flow level impr...,1
2,Onboarding New Hires,Introduce new employees to the company,"Cover policies, culture, and assign mentors fo...",Work,onboarding new hire introduce new employee com...,5
3,Evening Rollerblading Crew,Group inline skating,"Intermediate pace, explore safe bike paths.",Fitness,evening rollerblading crew group inline skatin...,1
4,Unmarked Door Admiration,missing,missing,Others,unmarked door admiration missing missing,2
...,...,...,...,...,...,...
561,Early American History,Study colonial America,Explore primary documents and settlement patte...,Academics,early american history study colonial america ...,0
562,Sales Funnel Analysis,Examine lead conversion rates,Identify drop-off points and strategize improv...,Work,sale funnel analysis examine lead conversion r...,5
563,Computer Networking Fundamentals,Basics of network protocols,"Understand LAN, WAN, TCP/IP models through exa...",Academics,computer networking fundamental basic network ...,0
564,Holiday Ornament Swap,Bring homemade ornaments,"Decorate a communal tree, trade decorations.",Social,holiday ornament swap bring homemade ornament ...,4
565,Community Potluck Picnic,Bring a dish to share,"Meet neighbors, taste varieties of homemade food.",Social,community potluck picnic bring dish share meet...,4

# Split the data

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(hashing_matrix, df['encoded_category'], test_size=0.2, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.80      0.83        15
           1       0.86      0.90      0.88        20
           2       0.42      0.80      0.55        10
           3       0.74      0.64      0.68        22
           4       0.78      0.64      0.70        22
           5       1.00      0.92      0.96        25

    accuracy                           0.78       114
   macro avg       0.77      0.78      0.77       114
weighted avg       0.81      0.78      0.79       114

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.61      0.93      0.74        15
           1       0.77      1.00      0.87        20
           2       1.00      0.80      0.89        10
           3       0.78      0.64      0.70        22
           4       0.81      0.59      0.68        22
           5       0.91      0.84      0.88        25

    accuracy                           0.79       114
   macro avg       0.81      0.80      0.79       114
weighted avg       0.81      0.79      0.79       114

In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.93      0.85        15
           1       0.80      1.00      0.89        20
           2       1.00      0.80      0.89        10
           3       0.78      0.82      0.80        22
           4       0.93      0.64      0.76        22
           5       1.00      1.00      1.00        25

    accuracy                           0.87       114
   macro avg       0.88      0.86      0.86       114
weighted avg       0.88      0.87      0.87       114

In [ ]:
from sklearn.svm import SVC
svm = SVC(kernel='linear')
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
print(classification_report(y_test, y_pred))
with open('svm.pkl', 'wb') as f:
    pickle.dump(svm, f)

              precision    recall  f1-score   support

           0       0.75      0.80      0.77        15
           1       0.91      1.00      0.95        20
           2       1.00      0.80      0.89        10
           3       0.72      0.82      0.77        22
           4       0.85      0.77      0.81        22
           5       0.96      0.88      0.92        25

    accuracy                           0.85       114
   macro avg       0.86      0.85      0.85       114
weighted avg       0.86      0.85      0.85       114

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.87      0.84        15
           1       0.83      1.00      0.91        20
           2       1.00      0.80      0.89        10
           3       0.75      0.82      0.78        22
           4       0.89      0.73      0.80        22
           5       1.00      0.96      0.98        25

    accuracy                           0.87       114
   macro avg       0.88      0.86      0.87       114
weighted avg       0.88      0.87      0.87       114

In [ ]:
df['category'].unique()

array(['Personal', 'Fitness', 'Work', 'Others', 'Academics', 'Social'],
      dtype=object)